/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * Market API
 * Документация к моему API
 * OpenAPI spec version: 1.0
 */

export * from './completeOrderDto';
export * from './createOrderDto';
export * from './loginDto';
export * from './lotDto';
export * from './openShopDto';
export * from './requestRegisterDto';
export * from './resendCodeDto';
export * from './reviewsDto';
export * from './verifyRegisterDto';